# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marcelo Carmona
name: Marcelo Carmona
email: marcelo@marcelocarmona.com
image: https://marcelocarmona.com/img/marcelo.jpg
description: > # this means to ignore newlines until "baseurl:"
  Articles on JavaScript, Angular and React
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcelocarmona.com" # the base hostname & protocol for your site
social:
  twitterURL: "https://twitter.com/CarmonaMarcelo"
  githubURL: "https://github.com/marcelocarmona"
  linkedinURL: "https://ar.linkedin.com/in/carmonamarcelo"

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
